server:
  port: 9502
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: worksheet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gmech
    username: ${GMECH_PG_USER}
    password: ${GMECH_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
      fetch-registry: true
      register-with-eureka: true

