server:
  port: 9500

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-register
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/register
        - id: auth-service-login
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/login
        - id: auth-service-logout
          uri: lb://auth-service
          predicates:
          - Path=/api/v1/auth/logout
        - id: auth-service-validate
          uri: lb://auth-service
          predicates:
          - Path=/api/v1/auth/validate
        - id: worksheet-service-save
          uri: lb://worksheet-service
          predicates:
          - Path=/api/v1/worksheet/save        
        - id: worksheet-service-all
          uri: lb://worksheet-service
          predicates:
          - Path=/api/v1/worksheet/all
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
      fetch-registry: true
      register-with-eureka: true