server:
  port: 9500

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-register
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/register
        - id: auth-service-login
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/login
        - id: auth-service-logout
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/logout
        - id: auth-service-validate
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/validate
        - id: customer-service-create
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/create   
          filters:
            - AuthenticationFilter  
        - id: customer-service-get
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/get   
          filters:
            - AuthenticationFilter
        - id: customer-service-getall
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/getall  
          filters:
            - AuthenticationFilter
        - id: vehicles-service-create
          uri: lb://vehicles-service
          predicates:
          - Path=/api/v1/vehicles/create
          filters:
            - AuthenticationFilter
        - id: vehicles-service-get
          uri: lb://vehicles-service
          predicates:
          - Path=/api/v1/vehicles/get
          filters:
            - AuthenticationFilter
        - id: vehicles-service-getall
          uri: lb://vehicles-service
          predicates:
          - Path=/api/v1/vehicles/getall
          filters:
            - AuthenticationFilter
        - id: stock-service-create
          uri: lb://stock-service
          predicates:
          - Path=/api/v1/stock/create
          filters:
            - AuthenticationFilter
        - id: stock-service-get
          uri: lb://stock-service
          predicates:
          - Path=/api/v1/stock/get
          filters:
            - AuthenticationFilter
        - id: stock-service-getall
          uri: lb://stock-service
          predicates:
          - Path=/api/v1/stock/getall
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
      fetch-registry: true
      register-with-eureka: true